- name: Setup Vprofile Bastion Host 
  hosts: localhost 
  connection: local 
  gather_facts: no 
  tasks: 
    - name: Import VPC setup variable 
      include_vars: vars/bastion_setup 
 
    - name: Import VPC setup Variable 
      include_vars: vars/output_vars 
 
    - name: Create vprofile ec2 key 
      ec2_key: 
        name: "{{ keyName }}" 
        region: "{{ region }}" 
      register: key_out 
 
    - name: Save private key into file bastion-key.pem 
      copy: 
        content: "{{ key_out.key.private_key }}" 
        dest: "./bastion-key.pem" 
        mode: 0600 
      when: key_out.changed 
 
    - name: Create Sec Grp for Bastion Host 
      ec2_group: 
        name: Bastion-host-sg 
        description: Allow port 22 from everywhere and all port within sg 
        vpc_id: "{{ vpcid }}" 
        region: "{{ region }}" 
        rules: 
          - proto: tcp 
            from_port: 22 
            to_port: 22 
            cidr_ip: "{{ MYIP }}" 
      register: BastionSG_out 
 
     
 
    - name: Creating Bastion Host
      amazon.aws.ec2_instance:
        key_name: "{{ keyName }}"
        region: "{{ region }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        exact_count: 1
        tags:
           Name: "Bastion_host"
           Project: Vprofile
           Owner: DevOps Team
        subnet_id: "{{ pubsub3id }}"
        security_groups:
           - Bastion-host-sg
        network:
           assign_public_ip: true
      register: bastionHost_out

    - name: Creating EC2 in privsub1 
      amazon.aws.ec2_instance: 
        key_name: "{{ keyName }}" 
        region: "{{ region }}" 
        instance_type: "{{ instanceType }}" 
        image_id: "{{ bastion_ami }}" 
        wait: yes 
        wait_timeout: 300 
        exact_count: 1
        tags: 
          Name: "privsub1Instance" 
          Project: Vprofile 
          Owner: DevOps Team  
        subnet_id: "{{ privsub1id }}" 
        network:
          assign_public_ip: true 
      register: privsub1Instance_out 
 
    - name: Creating EC2 in privsub3 
      amazon.aws.ec2_instance: 
         key_name: "{{ keyName }}" 
         region: "{{ region }}" 
         instance_type: "{{ instanceType }}" 
         image_id: "{{ bastion_ami }}" 
         wait: yes 
         wait_timeout: 300 
         exact_count: 1
         tags: 
           Name: "privsub3Instance" 
           Project: Vprofile 
           Owner: DevOps Team  
         subnet_id: "{{ privsub3id }}"
         security_groups:
           - Bastion-host-sg
         network:
           assign_public_ip: true 
      register: privsub3Instance_out

